In [1]:
import pandas as pd
import os

In [2]:
processed_path = os.path.join('..', 'data', 'processed')

## Idealista Price m2: 08-2016 até 11-2025 (1904 observações)

In [3]:
path_idealista = os.path.join(processed_path, 'Lisboa_freguesias_preco_m2_long_imputed.csv')

target = pd.read_csv(path_idealista)

In [4]:
target

,date,Year,Month,parish,price_m2,imputed_flag
0,2016-08-01,2016,8,Alvalade,11.100000,0
1,2016-08-01,2016,8,Areeiro,11.100000,0
2,2016-08-01,2016,8,Arroios,11.800000,0
3,2016-08-01,2016,8,Avenidas Novas,12.100000,0
4,2016-08-01,2016,8,Belém,10.433333,1
...,...,...,...,...,...,...
1899,2025-11-01,2025,11,Penha de França,20.000000,0
1900,2025-11-01,2025,11,Santa Maria Maior,27.900000,0
1901,2025-11-01,2025,11,Santo António,28.300000,0
1902,2025-11-01,2025,11,São Domingos de Benfica,17.800000,0
1903,2025-11-01,2025,11,São Vicente,24.300000,0

## POIS: Static variables

In [5]:
pois = pd.read_csv(os.path.join(processed_path, 'POIS_freguesias_lisboa.csv'))
pois = pois.rename(columns={'freguesia': 'parish'})

# merge only by Freguesia because POIS dataset dows not have month or year, is static for the parishes
merged_data = pd.merge(target, pois, on='parish', how='left')
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1904 entries, 0 to 1903
Data columns (total 27 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   date                                            1904 non-null   object
 1   Year                                            1904 non-null   int64
 2   Month                                           1904 non-null   int64
 3   parish                                          1904 non-null   object
 4   price_m2                                        1904 non-null   float64
 5   imputed_flag                                    1904 non-null   int64
 6   Num_Estacoes_Metro                              1904 non-null   int64
 7   Num_Estacoes_Comboio                            1904 non-null   int64
 8   Num_Prestadores_Saude                           1904 non-null   int64
 9   Area_km2                                        1904 non-null   float64
 10  Densidade_Estacoes_Metro_km2                    1904 non-null   float64
 11  Densidade_Estacoes_Comboio_km2                  1904 non-null   float64
 12  Densidade_Prestadores_Saude_km2                 1904 non-null   float64
 13  Num_Estabelecimentos_Ensino_Superior            1904 non-null   int64
 14  Densidade_Estabelecimentos_Ensino_Superior_km2  1904 non-null   float64
 15  Num_Escolas_Publicas                            1904 non-null   int64
 16  Densidade_Escolas_Publicas_km2                  1904 non-null   float64
 17  Num_Escolas_Privadas                            1904 non-null   int64
 18  Densidade_Escolas_Privadas_km2                  1904 non-null   float64
 19  Num_Jardins_Parques_Urbanos                     1904 non-null   int64
 20  Densidade_Jardins_Parques_Urbanos_km2           1904 non-null   float64
 21  Num_Museus                                      1904 non-null   int64
 22  Densidade_Museus_km2                            1904 non-null   float64
 23  Num_Mercados                                    1904 non-null   int64
 24  Densidade_Mercados_km2                          1904 non-null   float64
 25  Num_Supermercados                               1904 non-null   int64
 26  Densidade_Supermercados_km2                     1904 non-null   float64
dtypes: float64(12), int64(13), object(2)
memory usage: 401.8+ KB

## VIIRS - Monthly Mean Nighttime Radiance
Proxy for nocturnal economic and tourist activity intensity.

In [6]:
viirs = pd.read_csv(os.path.join(processed_path, 'VIIRS_Lisboa_Freguesias_2015_2025.csv'))
viirs = viirs.rename(columns={'Freguesia': 'parish', "mean": "MeanNightimeRadianceVIIRS"})
viirs['Year'] = viirs['Year'].astype(int)
viirs['Month'] = viirs['Month'].astype(int)

In [7]:
merged_data = pd.merge(merged_data, viirs[['parish', 'Year', 'Month', 'MeanNightimeRadianceVIIRS']], on=['parish', 'Year', 'Month'], how='left')
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1904 entries, 0 to 1903
Data columns (total 28 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   date                                            1904 non-null   object
 1   Year                                            1904 non-null   int64
 2   Month                                           1904 non-null   int64
 3   parish                                          1904 non-null   object
 4   price_m2                                        1904 non-null   float64
 5   imputed_flag                                    1904 non-null   int64
 6   Num_Estacoes_Metro                              1904 non-null   int64
 7   Num_Estacoes_Comboio                            1904 non-null   int64
 8   Num_Prestadores_Saude                           1904 non-null   int64
 9   Area_km2                                        1904 non-null   float64
 10  Densidade_Estacoes_Metro_km2                    1904 non-null   float64
 11  Densidade_Estacoes_Comboio_km2                  1904 non-null   float64
 12  Densidade_Prestadores_Saude_km2                 1904 non-null   float64
 13  Num_Estabelecimentos_Ensino_Superior            1904 non-null   int64
 14  Densidade_Estabelecimentos_Ensino_Superior_km2  1904 non-null   float64
 15  Num_Escolas_Publicas                            1904 non-null   int64
 16  Densidade_Escolas_Publicas_km2                  1904 non-null   float64
 17  Num_Escolas_Privadas                            1904 non-null   int64
 18  Densidade_Escolas_Privadas_km2                  1904 non-null   float64
 19  Num_Jardins_Parques_Urbanos                     1904 non-null   int64
 20  Densidade_Jardins_Parques_Urbanos_km2           1904 non-null   float64
 21  Num_Museus                                      1904 non-null   int64
 22  Densidade_Museus_km2                            1904 non-null   float64
 23  Num_Mercados                                    1904 non-null   int64
 24  Densidade_Mercados_km2                          1904 non-null   float64
 25  Num_Supermercados                               1904 non-null   int64
 26  Densidade_Supermercados_km2                     1904 non-null   float64
 27  MeanNightimeRadianceVIIRS                       1904 non-null   float64
dtypes: float64(13), int64(13), object(2)
memory usage: 416.6+ KB

## RJUE - Alvaras e Pedidos

In [8]:
rjue_alvaras = pd.read_csv(os.path.join(processed_path, 'RJUE_dados_urbanismo_alvaras.csv'))
rjue_pedidos = pd.read_csv(os.path.join(processed_path, 'RJUE_dados_urbanismo_pedidos.csv'))

In [9]:
freguesias_precos = set(merged_data['parish'].unique())
freguesias_rjue = set(rjue_pedidos['Freguesia'].unique())

# 2. Encontrar quem não tem par
apenas_no_preço = freguesias_precos - freguesias_rjue
apenas_no_rjue = freguesias_rjue - freguesias_precos

print(f"🚩 No Idealista mas não no RJUE: {apenas_no_preço}")
print(f"🚩 No RJUE mas não no Idealista: {apenas_no_rjue}")

🚩 No Idealista mas não no RJUE: {'São Domingos de Benfica', 'Parque das Nações', 'Penha de França', 'Campo de Ourique'}
🚩 No RJUE mas não no Idealista: {'São Domingos De Benfica', 'Campo De Ourique', 'Penha De França', 'Parque Das Nações'}

In [ ]:
mapa_freguesias = {
    'São Domingos De Benfica': 'São Domingos de Benfica',
    'Campo De Ourique': 'Campo de Ourique',
    'Parque Das Nações': 'Parque das Nações',
    'Penha De França': 'Penha de França'
}

# Aplicar a correção nos datasets RJUE
rjue_pedidos['Freguesia'] = rjue_pedidos['Freguesia'].replace(mapa_freguesias)
rjue_alvaras['Freguesia'] = rjue_alvaras['Freguesia'].replace(mapa_freguesias)

# Verificar se agora os conjuntos são idênticos
diff = set(merged_data['parish'].unique()) ^ set(rjue_pedidos['Freguesia'].unique())
if not diff:
    print("✅ Sucesso! As freguesias estão 100% sincronizadas.")
else:
    print(f"⚠️ Ainda existem diferenças: {diff}")

✅ Sucesso! As freguesias estão 100% sincronizadas.

In [11]:
df_pedidos_join = rjue_pedidos.rename(columns={'Freguesia': 'parish', 'AnoMes': 'date_key'})
df_alvaras_join = rjue_alvaras.rename(columns={'Freguesia': 'parish', 'AnoMes': 'date_key'})

# 2. PREPARAÇÃO DO DATASET PRINCIPAL (image_7ce641)
# Criamos uma 'date_key' (YYYY-MM) a partir de Year e Month para o merge ser exato
merged_data['date_key'] = (
    merged_data['Year'].astype(str) + '-' + 
    merged_data['Month'].astype(str).str.zfill(2)
)

In [12]:
# 3. O MEGA-MERGE (Left Join)
# Começamos pelo dataset de preços para não perder nenhuma linha do Idealista
final_df = pd.merge(merged_data, df_pedidos_join, on=['parish', 'date_key'], how='left')
final_df = pd.merge(final_df, df_alvaras_join, on=['parish', 'date_key'], how='left')

In [13]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1904 entries, 0 to 1903
Data columns (total 45 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   date                                            1904 non-null   object
 1   Year                                            1904 non-null   int64
 2   Month                                           1904 non-null   int64
 3   parish                                          1904 non-null   object
 4   price_m2                                        1904 non-null   float64
 5   imputed_flag                                    1904 non-null   int64
 6   Num_Estacoes_Metro                              1904 non-null   int64
 7   Num_Estacoes_Comboio                            1904 non-null   int64
 8   Num_Prestadores_Saude                           1904 non-null   int64
 9   Area_km2                                        1904 non-null   float64
 10  Densidade_Estacoes_Metro_km2                    1904 non-null   float64
 11  Densidade_Estacoes_Comboio_km2                  1904 non-null   float64
 12  Densidade_Prestadores_Saude_km2                 1904 non-null   float64
 13  Num_Estabelecimentos_Ensino_Superior            1904 non-null   int64
 14  Densidade_Estabelecimentos_Ensino_Superior_km2  1904 non-null   float64
 15  Num_Escolas_Publicas                            1904 non-null   int64
 16  Densidade_Escolas_Publicas_km2                  1904 non-null   float64
 17  Num_Escolas_Privadas                            1904 non-null   int64
 18  Densidade_Escolas_Privadas_km2                  1904 non-null   float64
 19  Num_Jardins_Parques_Urbanos                     1904 non-null   int64
 20  Densidade_Jardins_Parques_Urbanos_km2           1904 non-null   float64
 21  Num_Museus                                      1904 non-null   int64
 22  Densidade_Museus_km2                            1904 non-null   float64
 23  Num_Mercados                                    1904 non-null   int64
 24  Densidade_Mercados_km2                          1904 non-null   float64
 25  Num_Supermercados                               1904 non-null   int64
 26  Densidade_Supermercados_km2                     1904 non-null   float64
 27  MeanNightimeRadianceVIIRS                       1904 non-null   float64
 28  date_key                                        1904 non-null   object
 29  Stock_12M_PED_Nova_Construcao_Area              1904 non-null   float64
 30  Stock_12M_PED_Reabilitacao_Area                 1904 non-null   float64
 31  Stock_12M_PED_Nova_Construcao_Count             1904 non-null   float64
 32  Stock_12M_PED_Reabilitacao_Count                1904 non-null   float64
 33  Stock_12M_PED_Demolicao_Area                    1904 non-null   float64
 34  Stock_12M_PED_Demolicao_Count                   1904 non-null   float64
 35  Racio_Gentrificacao_PED_Area                    1904 non-null   float64
 36  Racio_Gentrificacao_PED_Count                   1904 non-null   float64
 37  Stock_12M_ALV_Nova_Construcao_Area              1904 non-null   float64
 38  Stock_12M_ALV_Reabilitacao_Area                 1904 non-null   float64
 39  Stock_12M_ALV_Nova_Construcao_Count             1904 non-null   float64
 40  Stock_12M_ALV_Reabilitacao_Count                1904 non-null   float64
 41  Stock_12M_ALV_Demolicao_Area                    1904 non-null   float64
 42  Stock_12M_ALV_Demolicao_Count                   1904 non-null   float64
 43  Racio_Gentrificacao_ALV_Area                    1904 non-null   float64
 44  Racio_Gentrificacao_ALV_Count                   1904 non-null   float64
dtypes: float64(29), int64(13), object(3)
memory usage: 669.5+ KB

## RNAL

In [14]:
# Merge with RNAL_variaveis_mensaias_freguesias_2008_2025.csv
rnals = pd.read_csv(os.path.join(processed_path, 'RNAL_dataset_final.csv'))
rnals = rnals.rename(columns={'Freguesia': 'parish', 'Ano': 'Year', 'Mes': 'Month'})
# Levas apenas o stock histórico e as métricas de pressão.
colunas_al = [
    'parish', 'Year', 'Month', 
    'Densidade_AL_km2', 'Densidade_Capacidade_km2',
    'capacidade_media_por_al', 'al_growth_rate', 'racio_mercado_informal'
]
rnals = rnals[colunas_al]
rnals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5112 entries, 0 to 5111
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   parish                    5112 non-null   object
 1   Year                      5112 non-null   int64
 2   Month                     5112 non-null   int64
 3   Densidade_AL_km2          5112 non-null   float64
 4   Densidade_Capacidade_km2  5112 non-null   float64
 5   capacidade_media_por_al   5112 non-null   float64
 6   al_growth_rate            5112 non-null   float64
 7   racio_mercado_informal    5112 non-null   float64
dtypes: float64(5), int64(2), object(1)
memory usage: 319.6+ KB

In [15]:
# Merge the datasets on 'parish', 'Year', and 'Month'
merged_data = pd.merge(final_df, rnals, on=['parish', 'Year', 'Month'], how='left')
merged_data

,date,Year,Month,parish,price_m2,imputed_flag,Num_Estacoes_Metro,Num_Estacoes_Comboio,Num_Prestadores_Saude,Area_km2,...,Stock_12M_ALV_Reabilitacao_Count,Stock_12M_ALV_Demolicao_Area,Stock_12M_ALV_Demolicao_Count,Racio_Gentrificacao_ALV_Area,Racio_Gentrificacao_ALV_Count,Densidade_AL_km2,Densidade_Capacidade_km2,capacidade_media_por_al,al_growth_rate,racio_mercado_informal
0,2016-08-01,2016,8,Alvalade,11.100000,0,3,1,4,5.34,...,25.0,0.000000,0.0,1.079371e+01,24.997500,5.430712,43.632959,8.034483,0.260870,0.000000
1,2016-08-01,2016,8,Areeiro,11.100000,0,1,0,0,1.74,...,12.0,0.000000,0.0,4.415204e+07,120000.000000,27.011494,282.183908,10.446809,0.000000,0.148936
2,2016-08-01,2016,8,Arroios,11.800000,0,4,0,6,2.13,...,44.0,561.459961,1.0,2.534457e+01,21.998900,205.633803,1816.901408,8.835616,0.050360,0.013699
3,2016-08-01,2016,8,Avenidas Novas,12.100000,0,6,1,5,2.99,...,47.0,0.000000,0.0,3.175345e+01,23.498825,38.795987,494.648829,12.750000,0.195876,0.008621
4,2016-08-01,2016,8,Belém,10.433333,1,0,1,1,10.43,...,33.0,885.103027,11.0,5.005450e+00,4.124948,5.656759,30.009588,5.305085,0.053571,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1899,2025-11-01,2025,11,Penha de França,20.000000,0,0,0,2,2.71,...,1.0,0.000000,0.0,1.253799e+06,10000.000000,213.653137,1278.966790,5.986183,0.000000,0.006908
1900,2025-11-01,2025,11,Santa Maria Maior,27.900000,0,5,1,2,3.01,...,11.0,0.000000,0.0,4.400366e+07,110000.000000,1438.205980,7757.475083,5.393855,0.000000,0.011550
1901,2025-11-01,2025,11,Santo António,28.300000,0,3,0,6,1.49,...,11.0,0.000000,0.0,1.100448e+08,110000.000000,1024.832215,6693.959732,6.531762,0.000000,0.035363
1902,2025-11-01,2025,11,São Domingos de Benfica,17.800000,0,3,1,5,4.29,...,0.0,0.000000,0.0,0.000000e+00,0.000000,38.461538,245.687646,6.387879,0.000000,0.000000
1903,2025-11-01,2025,11,São Vicente,24.300000,0,1,1,1,1.99,...,2.0,0.000000,0.0,8.135635e+06,20000.000000,751.758794,3882.412060,5.164439,0.000000,0.008021

In [16]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1904 entries, 0 to 1903
Data columns (total 50 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   date                                            1904 non-null   object
 1   Year                                            1904 non-null   int64
 2   Month                                           1904 non-null   int64
 3   parish                                          1904 non-null   object
 4   price_m2                                        1904 non-null   float64
 5   imputed_flag                                    1904 non-null   int64
 6   Num_Estacoes_Metro                              1904 non-null   int64
 7   Num_Estacoes_Comboio                            1904 non-null   int64
 8   Num_Prestadores_Saude                           1904 non-null   int64
 9   Area_km2                                        1904 non-null   float64
 10  Densidade_Estacoes_Metro_km2                    1904 non-null   float64
 11  Densidade_Estacoes_Comboio_km2                  1904 non-null   float64
 12  Densidade_Prestadores_Saude_km2                 1904 non-null   float64
 13  Num_Estabelecimentos_Ensino_Superior            1904 non-null   int64
 14  Densidade_Estabelecimentos_Ensino_Superior_km2  1904 non-null   float64
 15  Num_Escolas_Publicas                            1904 non-null   int64
 16  Densidade_Escolas_Publicas_km2                  1904 non-null   float64
 17  Num_Escolas_Privadas                            1904 non-null   int64
 18  Densidade_Escolas_Privadas_km2                  1904 non-null   float64
 19  Num_Jardins_Parques_Urbanos                     1904 non-null   int64
 20  Densidade_Jardins_Parques_Urbanos_km2           1904 non-null   float64
 21  Num_Museus                                      1904 non-null   int64
 22  Densidade_Museus_km2                            1904 non-null   float64
 23  Num_Mercados                                    1904 non-null   int64
 24  Densidade_Mercados_km2                          1904 non-null   float64
 25  Num_Supermercados                               1904 non-null   int64
 26  Densidade_Supermercados_km2                     1904 non-null   float64
 27  MeanNightimeRadianceVIIRS                       1904 non-null   float64
 28  date_key                                        1904 non-null   object
 29  Stock_12M_PED_Nova_Construcao_Area              1904 non-null   float64
 30  Stock_12M_PED_Reabilitacao_Area                 1904 non-null   float64
 31  Stock_12M_PED_Nova_Construcao_Count             1904 non-null   float64
 32  Stock_12M_PED_Reabilitacao_Count                1904 non-null   float64
 33  Stock_12M_PED_Demolicao_Area                    1904 non-null   float64
 34  Stock_12M_PED_Demolicao_Count                   1904 non-null   float64
 35  Racio_Gentrificacao_PED_Area                    1904 non-null   float64
 36  Racio_Gentrificacao_PED_Count                   1904 non-null   float64
 37  Stock_12M_ALV_Nova_Construcao_Area              1904 non-null   float64
 38  Stock_12M_ALV_Reabilitacao_Area                 1904 non-null   float64
 39  Stock_12M_ALV_Nova_Construcao_Count             1904 non-null   float64
 40  Stock_12M_ALV_Reabilitacao_Count                1904 non-null   float64
 41  Stock_12M_ALV_Demolicao_Area                    1904 non-null   float64
 42  Stock_12M_ALV_Demolicao_Count                   1904 non-null   float64
 43  Racio_Gentrificacao_ALV_Area                    1904 non-null   float64
 44  Racio_Gentrificacao_ALV_Count                   1904 non-null   float64
 45  Densidade_AL_km2                                1904 non-null   float64
 46  Densidade_Capacidade_km2                        1904 non-null   float64
 47  capacidade_media_por_al                         1904 non-null   float64
 48  al_growth_rate                                  1904 non-null   float64
 49  racio_mercado_informal                          1904 non-null   float64
dtypes: float64(34), int64(13), object(3)
memory usage: 743.9+ KB

## CENSOS - Static Variable

In [17]:
censos = pd.read_csv(os.path.join(processed_path, 'CENSOS_dados.csv'))
censos = censos.rename(columns={'Freguesia': 'parish'})
merged_data = pd.merge(merged_data, censos, on='parish', how='left')
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1904 entries, 0 to 1903
Data columns (total 85 columns):
 #   Column                                                                              Non-Null Count  Dtype
---  ------                                                                              --------------  -----
 0   date                                                                                1904 non-null   object
 1   Year                                                                                1904 non-null   int64
 2   Month                                                                               1904 non-null   int64
 3   parish                                                                              1904 non-null   object
 4   price_m2                                                                            1904 non-null   float64
 5   imputed_flag                                                                        1904 non-null   int64
 6   Num_Estacoes_Metro                                                                  1904 non-null   int64
 7   Num_Estacoes_Comboio                                                                1904 non-null   int64
 8   Num_Prestadores_Saude                                                               1904 non-null   int64
 9   Area_km2                                                                            1904 non-null   float64
 10  Densidade_Estacoes_Metro_km2                                                        1904 non-null   float64
 11  Densidade_Estacoes_Comboio_km2                                                      1904 non-null   float64
 12  Densidade_Prestadores_Saude_km2                                                     1904 non-null   float64
 13  Num_Estabelecimentos_Ensino_Superior                                                1904 non-null   int64
 14  Densidade_Estabelecimentos_Ensino_Superior_km2                                      1904 non-null   float64
 15  Num_Escolas_Publicas                                                                1904 non-null   int64
 16  Densidade_Escolas_Publicas_km2                                                      1904 non-null   float64
 17  Num_Escolas_Privadas                                                                1904 non-null   int64
 18  Densidade_Escolas_Privadas_km2                                                      1904 non-null   float64
 19  Num_Jardins_Parques_Urbanos                                                         1904 non-null   int64
 20  Densidade_Jardins_Parques_Urbanos_km2                                               1904 non-null   float64
 21  Num_Museus                                                                          1904 non-null   int64
 22  Densidade_Museus_km2                                                                1904 non-null   float64
 23  Num_Mercados                                                                        1904 non-null   int64
 24  Densidade_Mercados_km2                                                              1904 non-null   float64
 25  Num_Supermercados                                                                   1904 non-null   int64
 26  Densidade_Supermercados_km2                                                         1904 non-null   float64
 27  MeanNightimeRadianceVIIRS                                                           1904 non-null   float64
 28  date_key                                                                            1904 non-null   object
 29  Stock_12M_PED_Nova_Construcao_Area                                                  1904 non-null   float64
 30  Stock_12M_PED_Reabilitacao_Area                                                     1904 non-null   float64
 31  Stock_12M_PED_Nova_Construcao_Count                                                 1904 non-null   float64
 32  Stock_12M_PED_Reabilitacao_Count                                                    1904 non-null   float64
 33  Stock_12M_PED_Demolicao_Area                                                        1904 non-null   float64
 34  Stock_12M_PED_Demolicao_Count                                                       1904 non-null   float64
 35  Racio_Gentrificacao_PED_Area                                                        1904 non-null   float64
 36  Racio_Gentrificacao_PED_Count                                                       1904 non-null   float64
 37  Stock_12M_ALV_Nova_Construcao_Area                                                  1904 non-null   float64
 38  Stock_12M_ALV_Reabilitacao_Area                                                     1904 non-null   float64
 39  Stock_12M_ALV_Nova_Construcao_Count                                                 1904 non-null   float64
 40  Stock_12M_ALV_Reabilitacao_Count                                                    1904 non-null   float64
 41  Stock_12M_ALV_Demolicao_Area                                                        1904 non-null   float64
 42  Stock_12M_ALV_Demolicao_Count                                                       1904 non-null   float64
 43  Racio_Gentrificacao_ALV_Area                                                        1904 non-null   float64
 44  Racio_Gentrificacao_ALV_Count                                                       1904 non-null   float64
 45  Densidade_AL_km2                                                                    1904 non-null   float64
 46  Densidade_Capacidade_km2                                                            1904 non-null   float64
 47  capacidade_media_por_al                                                             1904 non-null   float64
 48  al_growth_rate                                                                      1904 non-null   float64
 49  racio_mercado_informal                                                              1904 non-null   float64
 50  Indice_Envelhecimento_2021                                                          1904 non-null   float64
 51  Proporcao_Populacao_Residente_Estrangeira_2021                                      1904 non-null   float64
 52  Densidade_Populacional_2021                                                         1904 non-null   object
 53  Variacao_Relativa_Populacao_Residente_2011_2021                                     1904 non-null   float64
 54  Número_Residencia_Habitual_2011                                                     1904 non-null   int64
 55  Número_Residencia_Secundaria_2011                                                   1904 non-null   int64
 56  Número_Vago_Venda_Arrendamento_2011                                                 1904 non-null   int64
 57  Número_Vago_Outros_Motivos_2011                                                     1904 non-null   int64
 58  Número_Residencia_Habitual_2021                                                     1904 non-null   int64
 59  Número_Residencia_Secundaria_2021                                                   1904 non-null   int64
 60  Número_Vago_Venda_Arrendamento_2021                                                 1904 non-null   int64
 61  Número_Vago_Outros_Motivos_2021                                                     1904 non-null   int64
 62  Número_Total_Alojamentos_2021                                                       1904 non-null   int64
 63  Area_Freguesia_km2                                                                  1904 non-null   float64
 64  Densidade_Alojamentos_Familiares_Classicos_2021                                     1904 non-null   float64
 65  Percentagem_Residencia_Habitual_2021                                                1904 non-null   float64
 66  Percentagem_Residencia_Secundaria_2021                                              1904 non-null   float64
 67  Indice_Pressao_Habitacional_2021                                                    1904 non-null   float64
 68  Pct_Fogos_Vagos_2021                                                                1904 non-null   float64
 69  Número_Agregados_1_Pessoa_2021                                                      1904 non-null   int64
 70  Número_Agregados_2_Pessoas_2021                                                     1904 non-null   int64
 71  Número_Agregados_3_Pessoas_2021                                                     1904 non-null   int64
 72  Número_Agregados_4_Pessoas_2021                                                     1904 non-null   int64
 73  Número_Agregados_5_Pessoas_2021                                                     1904 non-null   int64
 74  Número_Agregados_6_Pessoas_2021                                                     1904 non-null   int64
 75  Número_Agregados_7_Pessoas_2021                                                     1904 non-null   int64
 76  Número_Agregados_8_Pessoas_2021                                                     1904 non-null   int64
 77  Número_Agregados_9_Mais_Pessoas_2021                                                1904 non-null   int64
 78  Total_Agregados_2021                                                                1904 non-null   int64
 79  Dimensao_Media_Agregados_2021                                                       1904 non-null   float64
 80  Proporcao_Populacao_Residente_Ensino_Superior_Completo_2021                         1904 non-null   float64
 81  Variacao_absoluta_Proporcao_Populacao_Residente_Ensino_Superior_Completo_2011_2021  1904 non-null   float64
 82  PCT_Edificios_Antigos                                                               1904 non-null   float64
 83  PCT_Edificios_Intermediarios                                                        1904 non-null   float64
 84  PCT_Edificios_Modernos                                                              1904 non-null   float64
dtypes: float64(49), int64(32), object(4)
memory usage: 1.2+ MB

In [18]:
merged_data.to_csv(os.path.join(processed_path, 'final_dataset.csv'), index=False)