In [1]:
import pandas as pd
import geopandas as gpd
import os

In [2]:
raw_path = os.path.join('..', 'data', 'raw')

In [3]:
areas_freguesias = {
    'Ajuda': 2.88,
    'Alcântara': 5.07,
    'Alvalade': 5.34,
    'Areeiro': 1.74,
    'Arroios': 2.13,
    'Avenidas Novas': 2.99,
    'Beato': 2.48,
    'Belém': 10.43,
    'Benfica': 8.02,
    'Campo de Ourique': 1.65,
    'Campolide': 2.77,
    'Carnide': 3.69,
    'Estrela': 4.60,
    'Lumiar': 6.57,
    'Marvila': 7.12,
    'Misericórdia': 2.19,
    'Olivais': 8.09,
    'Parque das Nações': 5.44,
    'Penha de França': 2.71,
    'Santa Clara': 3.36,
    'Santa Maria Maior': 3.01,
    'Santo António': 1.49,
    'São Domingos de Benfica': 4.29,
    'São Vicente': 1.99
}

In [4]:
shp_metro = gpd.read_file(os.path.join(raw_path, 'estacoes_metro', 'Estações_de_Metro.shp'))
shp_comboio = gpd.read_file(os.path.join(raw_path, 'estacoes_comboio', 'Estações_de_Comboio.shp'))
shp_saude = gpd.read_file(os.path.join(raw_path, 'prestacao_servicos_saude', 'Prestação_de_Cuidados.shp'))

In [5]:
shp_metro.head()

,COD_SIG,IDTIPO,NOME,SITUACAO,LINHA,GlobalID,geometry
0,35,9008,Cais do Sodré,Linha existente,Verde,7884caa2-5bde-4d0f-abad-5aa9d096f561,POINT (-1018151.212 4679662.08)
1,34,9008,Terreiro do Paço,Linha existente,Azul,b59aa474-fcbd-4352-9052-a817324a5af8,POINT (-1016814.759 4679806.766)
2,33,9008,Baixa Chiado,Linha existente,Azul/Verde,19e6ce36-b428-49fb-96ea-a4adaf3c5589,POINT (-1017476.911 4680297.608)
3,37,9008,Santa Apolónia,Linha existente,Azul,2654f880-1ae5-41ed-82f8-5170aaedb9ee,POINT (-1015493.578 4680776.12)
4,43,9008,Rossio,Linha existente,Verde,d9644ad7-394e-4aa0-b591-aefc8731b079,POINT (-1017224.77 4680792.459)

In [6]:
shp_comboio

,COD_SIG,IDTIPO,ID,NOME,GlobalID,geometry
0,13,9007,12,Santos,90c987a9-8074-4325-9ca2-ac5413f78181,POINT (-1019188.103 4679654.696)
1,14,9007,13,Rossio,6f77887d-eda3-44fa-9b15-b17e117c0a2b,POINT (-1017678.725 4680883.312)
2,4,9007,4,Marvila,8506d252-c355-4a0f-92a7-b1207c6cfb68,POINT (-1013956.853 4684381.437)
3,10,9007,9,Benfica,bdd5ff93-8808-4dbb-8928-077eb9f5b0e9,POINT (-1024092.783 4685121.432)
4,15,9007,14,Caís do Sodré,9d857494-41e5-42be-8de0-45cf64b6ed06,POINT (-1018115.514 4679638.401)
5,8,9007,7,Sete Rios,01a493ce-e00a-4212-a47c-6cfac8aabc38,POINT (-1020463.519 4684501.191)
6,18,9007,16,Santa Apolónia,92ee0a88-c921-4ec6-888f-64bde706f821,POINT (-1015431.696 4680924.654)
7,5,9007,5,Roma Areeiro,e3d9d2e5-6f0c-4775-a23e-e1799a9920b3,POINT (-1016803.005 4685319.9)
8,12,9007,11,Alcântara Mar,60cb37db-bca5-44e8-85e1-e33c9f140ad4,POINT (-1021210.644 4679140.968)
9,3,9007,3,Chelas,49313797-0989-4d8c-88ea-c89d5e459f8f,POINT (-1015070.139 4684325.738)
10,6,9007,6,Entrecampos,793376d9-43f5-49dc-ad06-6ee52549c56f,POINT (-1018455.182 4685125.46)
11,17,9007,15,Alcântara Terra,5db94562-2ba2-4508-99c3-8fa06567d89f,POINT (-1021158.64 4679859.845)
12,9,9007,8,Belém,e3f3205d-cbb8-438c-8e55-d3b80b1aa741,POINT (-1023832.578 4678249.856)
13,1,9007,1,Braço de Prata,6eb71f57-c0a5-48d1-bea4-6974fed121d0,POINT (-1013319.638 4685509.32)
14,2,9007,2,Oriente,f348254a-8039-4fde-944c-71207531639f,POINT (-1012901.292 4688464.885)
15,11,9007,10,Campolide,44a5386f-1fb0-4f1c-b2fb-6e537caf1fc6,POINT (-1020581.258 4683393.374)

In [7]:
caop = gpd.read_file(os.path.join(raw_path, 'Continente_CAOP2024_1.gpkg'))

c:\Users\migue\AppData\Local\Programs\Python\Python314\Lib\site-packages\pyogrio\geopandas.py:382: UserWarning: More than one layer found in 'Continente_CAOP2024_1.gpkg': 'cont_areas_administrativas' (default), 'cont_distritos', 'cont_freguesias', 'cont_municipios', 'cont_nuts1', 'cont_nuts2', 'cont_nuts3', 'cont_trocos', 'layer_styles', 'inf_fonte_troco'. Specify layer parameter to avoid this warning.
  result = read_func(

In [8]:
caop.head()

,id,dtmnfr,freguesia,tipo_area_administrativa,municipio,distrito_ilha,nuts3,nuts2,nuts1,area_ha,perimetro_km,geometry
0,1,170642,União das freguesias de Viade de Baixo e Fervi...,Área Principal,Montalegre,Vila Real,Alto Tâmega e Barroso,Norte,Continente,4830.92,36,"POLYGON ((25914.068 230831.117, 25835.354 2298..."
1,2,170203,Beça,Área Principal,Boticas,Vila Real,Alto Tâmega e Barroso,Norte,Continente,2985.88,30,"POLYGON ((30648.239 226601.494, 30650.729 2266..."
2,3,170618,Negrões,Área Principal,Montalegre,Vila Real,Alto Tâmega e Barroso,Norte,Continente,2060.92,21,"POLYGON ((31281.463 227715.776, 31209.294 2277..."
3,4,170601,Cabril,Área Principal,Montalegre,Vila Real,Alto Tâmega e Barroso,Norte,Continente,7656.38,49,"POLYGON ((7305.233 239421.321, 8916.931 237618..."
4,5,170619,Outeiro,Área Principal,Montalegre,Vila Real,Alto Tâmega e Barroso,Norte,Continente,5231.54,35,"POLYGON ((12411.255 232126.871, 12399.795 2321..."

In [9]:
metro = shp_metro.to_crs(caop.crs)
comboio = shp_comboio.to_crs(caop.crs)
saude = shp_saude.to_crs(caop.crs)

In [10]:
print(metro.crs)
print(comboio.crs)
print(saude.crs)
print(caop.crs)

EPSG:3763
EPSG:3763
EPSG:3763
EPSG:3763

In [11]:
metro_freg = gpd.sjoin(metro, caop, how="inner", predicate='within')
comboio_freg = gpd.sjoin(comboio, caop, how="inner", predicate='within')
saude_freg = gpd.sjoin(saude, caop, how="inner", predicate='within')

In [12]:
# contagem estações de metro por freguesia de lisboa (incluir aquelas que têm 0 estações)
contagem_metro = (
    metro_freg
    .groupby('freguesia')
    .size()
    .reset_index(name='Num_Estacoes_Metro')
)

contagem_comboio = (
    comboio_freg
    .groupby('freguesia')
    .size()
    .reset_index(name='Num_Estacoes_Comboio')
)

contagem_saude = (
    saude_freg
    .groupby('freguesia')
    .size()
    .reset_index(name='Num_Prestadores_Saude')
)

In [13]:
contagem_metro

                  freguesia  Num_Estacoes_Metro
0                  Alvalade                   3
1                   Areeiro                   1
2                   Arroios                   4
3            Avenidas Novas                   6
4                     Beato                   1
5                   Benfica                   1
6                 Campolide                   1
7                   Carnide                   2
8            Encosta do Sol                   1
9     Falagueira-Venda Nova                   2
10                   Lumiar                   4
11                  Marvila                   2
12             Misericórdia                   1
13                 Odivelas                   2
14                  Olivais                   4
15        Parque das Nações                   2
16              Santa Clara                   1
17        Santa Maria Maior                   5
18            Santo António                   3
19  São Domingos de Benfica                   3
20              São Vicente                   1

In [14]:
contagem_comboio

                  freguesia  Num_Estacoes_Comboio
0                  Alvalade                     1
1            Avenidas Novas                     1
2                     Beato                     1
3                     Belém                     1
4                   Benfica                     1
5                 Campolide                     1
6                   Estrela                     3
7                   Marvila                     2
8              Misericórdia                     1
9         Parque das Nações                     1
10        Santa Maria Maior                     1
11  São Domingos de Benfica                     1
12              São Vicente                     1

In [15]:
metro_freg = gpd.sjoin(
    metro,
    caop,
    how='left',
    predicate='within'
)

comboio_freg = gpd.sjoin(
    comboio,
    caop,
    how='left',
    predicate='within'
)

saude_freg = gpd.sjoin(
    saude,
    caop,
    how='left',
    predicate='within'
)

In [16]:
comboio_freg

,COD_SIG,IDTIPO,ID,NOME,GlobalID,geometry,index_right,id,dtmnfr,freguesia,tipo_area_administrativa,municipio,distrito_ilha,nuts3,nuts2,nuts1,area_ha,perimetro_km
0,13,9007,12,Santos,90c987a9-8074-4325-9ca2-ac5413f78181,POINT (-88934.38 -106325.765),1951,1952,110660,Estrela,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,460.40,10
1,14,9007,13,Rossio,6f77887d-eda3-44fa-9b15-b17e117c0a2b,POINT (-87744.401 -105382.763),1929,1930,110665,Santa Maria Maior,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,301.16,9
2,4,9007,4,Marvila,8506d252-c355-4a0f-92a7-b1207c6cfb68,POINT (-84807.441 -102692.739),1920,1921,110621,Marvila,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,712.24,12
3,10,9007,9,Benfica,bdd5ff93-8808-4dbb-8928-077eb9f5b0e9,POINT (-92717.445 -102028.857),1910,1911,110608,Benfica,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,802.49,17
4,15,9007,14,Caís do Sodré,9d857494-41e5-42be-8de0-45cf64b6ed06,POINT (-88096.384 -106347.756),1914,1915,110661,Misericórdia,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,219.22,7
5,8,9007,7,Sete Rios,01a493ce-e00a-4212-a47c-6cfac8aabc38,POINT (-89888.442 -102543.819),1937,1938,110639,São Domingos de Benfica,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,429.43,10
6,18,9007,16,Santa Apolónia,92ee0a88-c921-4ec6-888f-64bde706f821,POINT (-85988.406 -105369.737),1949,1950,110667,São Vicente,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,198.58,7
7,5,9007,5,Roma Areeiro,e3d9d2e5-6f0c-4775-a23e-e1799a9920b3,POINT (-87022.453 -101938.782),1925,1926,110654,Alvalade,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,534.17,11
8,12,9007,11,Alcântara Mar,60cb37db-bca5-44e8-85e1-e33c9f140ad4,POINT (-90519.366 -106707.776),1951,1952,110660,Estrela,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,460.40,10
9,3,9007,3,Chelas,49313797-0989-4d8c-88ea-c89d5e459f8f,POINT (-85677.441 -102726.754),1897,1898,110607,Beato,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,248.38,8
10,6,9007,6,Entrecampos,793376d9-43f5-49dc-ad06-6ee52549c56f,POINT (-88314.451 -102075.802),1880,1881,110657,Avenidas Novas,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,299.45,9
11,17,9007,15,Alcântara Terra,5db94562-2ba2-4508-99c3-8fa06567d89f,POINT (-90472.376 -106148.783),1951,1952,110660,Estrela,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,460.40,10
12,9,9007,8,Belém,e3f3205d-cbb8-438c-8e55-d3b80b1aa741,POINT (-92576.346 -107377.791),1936,1937,110658,Belém,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,1042.76,16
13,1,9007,1,Braço de Prata,6eb71f57-c0a5-48d1-bea4-6974fed121d0,POINT (-84300.45 -101820.738),1920,1921,110621,Marvila,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,712.24,12
14,2,9007,2,Oriente,f348254a-8039-4fde-944c-71207531639f,POINT (-83949.476 -99525.752),1917,1918,110662,Parque das Nações,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,543.50,12
15,11,9007,10,Campolide,44a5386f-1fb0-4f1c-b2fb-6e537caf1fc6,POINT (-89990.143 -103404.548),1938,1939,110610,Campolide,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,277.43,9

In [17]:
# contagem estações de metro e comboio por freguesia de lisboa (incluir aquelas que têm 0 estações)
contagem_metro = (
    metro_freg
    .groupby('freguesia')
    .size()
    .reset_index(name='Num_Estacoes_Metro')
)

comboio_freg = (
    comboio_freg
    .groupby('freguesia')
    .size()
    .reset_index(name='Num_Estacoes_Comboio')
)

saude_freg = (
    saude_freg
    .groupby('freguesia')
    .size()
    .reset_index(name='Num_Prestadores_Saude')
)

In [18]:
# Merge com freguesias
freguesias = caop.merge(
    contagem_metro,
    on="freguesia",
    how="left"
)

freguesias = freguesias.merge(
    contagem_comboio,
    on="freguesia",
    how="left"
)

freguesias = freguesias.merge(
    contagem_saude,
    on="freguesia",
    how="left"
)

# Substituir NA por 0 (freguesias sem metro)
freguesias["Num_Estacoes_Metro"] = freguesias["Num_Estacoes_Metro"].fillna(0).astype(int)
freguesias["Num_Estacoes_Comboio"] = freguesias["Num_Estacoes_Comboio"].fillna(0).astype(int)
freguesias["Num_Prestadores_Saude"] = freguesias["Num_Prestadores_Saude"].fillna(0).astype(int)

In [19]:
#freguesias municipio de lisboa
freguesias_lisboa = freguesias[freguesias['municipio'] == 'Lisboa']
freguesias_lisboa.head()

,id,dtmnfr,freguesia,tipo_area_administrativa,municipio,distrito_ilha,nuts3,nuts2,nuts1,area_ha,perimetro_km,geometry,Num_Estacoes_Metro,Num_Estacoes_Comboio,Num_Prestadores_Saude
1871,1872,110618,Lumiar,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,657.49,13,"POLYGON ((-90553.744 -98069.442, -90546.315 -9...",4,0,5
1880,1881,110657,Avenidas Novas,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,299.45,9,"POLYGON ((-89451.01 -101982.892, -89449.065 -1...",6,1,5
1896,1897,110655,Areeiro,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,171.89,6,"POLYGON ((-85811.448 -102462.14, -85832.096 -1...",1,0,0
1897,1898,110607,Beato,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,248.38,8,"POLYGON ((-86369.427 -102823.157, -86350.965 -...",1,1,0
1910,1911,110608,Benfica,Área Principal,Lisboa,Lisboa,Grande Lisboa,Grande Lisboa,Continente,802.49,17,"POLYGON ((-94518.801 -105062.394, -94461.323 -...",1,1,3

In [20]:
## deixar só as colunas das freguesias e Num_
freguesias_lisboa = freguesias_lisboa[['freguesia', 'Num_Estacoes_Metro', 'Num_Estacoes_Comboio', 'Num_Prestadores_Saude']]
freguesias_lisboa['Area_km2'] = freguesias_lisboa['freguesia'].map(areas_freguesias)
freguesias_lisboa

,freguesia,Num_Estacoes_Metro,Num_Estacoes_Comboio,Num_Prestadores_Saude,Area_km2
1871,Lumiar,4,0,5,6.57
1880,Avenidas Novas,6,1,5,2.99
1896,Areeiro,1,0,0,1.74
1897,Beato,1,1,0,2.48
1910,Benfica,1,1,3,8.02
1914,Misericórdia,1,1,5,2.19
1917,Parque das Nações,2,1,1,5.44
1919,Olivais,4,0,3,8.09
1920,Marvila,2,2,2,7.12
1923,Santa Clara,1,0,0,3.36
1925,Alvalade,3,1,4,5.34
1926,Penha de França,0,0,2,2.71
1927,Santo António,3,0,6,1.49
1928,Arroios,4,0,6,2.13
1929,Santa Maria Maior,5,1,2,3.01
1930,Campo de Ourique,0,0,2,1.65
1931,Alcântara,0,0,4,5.07
1932,Ajuda,0,0,2,2.88
1936,Belém,0,1,1,10.43
1937,São Domingos de Benfica,3,1,5,4.29
1938,Campolide,1,1,1,2.77
1939,Carnide,2,0,2,3.69
1949,São Vicente,1,1,1,1.99
1951,Estrela,0,3,7,4.60

In [21]:
# desnsidade de estações de metro por km2
freguesias_lisboa['Densidade_Estacoes_Metro_km2'] = freguesias_lisboa['Num_Estacoes_Metro'] / freguesias_lisboa['Area_km2']
freguesias_lisboa['Densidade_Estacoes_Comboio_km2'] = freguesias_lisboa['Num_Estacoes_Comboio'] / freguesias_lisboa['Area_km2']
freguesias_lisboa['Densidade_Prestadores_Saude_km2'] = freguesias_lisboa['Num_Prestadores_Saude'] / freguesias_lisboa['Area_km2']
freguesias_lisboa

,freguesia,Num_Estacoes_Metro,Num_Estacoes_Comboio,Num_Prestadores_Saude,Area_km2,Densidade_Estacoes_Metro_km2,Densidade_Estacoes_Comboio_km2,Densidade_Prestadores_Saude_km2
1871,Lumiar,4,0,5,6.57,0.608828,0.000000,0.761035
1880,Avenidas Novas,6,1,5,2.99,2.006689,0.334448,1.672241
1896,Areeiro,1,0,0,1.74,0.574713,0.000000,0.000000
1897,Beato,1,1,0,2.48,0.403226,0.403226,0.000000
1910,Benfica,1,1,3,8.02,0.124688,0.124688,0.374065
1914,Misericórdia,1,1,5,2.19,0.456621,0.456621,2.283105
1917,Parque das Nações,2,1,1,5.44,0.367647,0.183824,0.183824
1919,Olivais,4,0,3,8.09,0.494438,0.000000,0.370828
1920,Marvila,2,2,2,7.12,0.280899,0.280899,0.280899
1923,Santa Clara,1,0,0,3.36,0.297619,0.000000,0.000000
1925,Alvalade,3,1,4,5.34,0.561798,0.187266,0.749064
1926,Penha de França,0,0,2,2.71,0.000000,0.000000,0.738007
1927,Santo António,3,0,6,1.49,2.013423,0.000000,4.026846
1928,Arroios,4,0,6,2.13,1.877934,0.000000,2.816901
1929,Santa Maria Maior,5,1,2,3.01,1.661130,0.332226,0.664452
1930,Campo de Ourique,0,0,2,1.65,0.000000,0.000000,1.212121
1931,Alcântara,0,0,4,5.07,0.000000,0.000000,0.788955
1932,Ajuda,0,0,2,2.88,0.000000,0.000000,0.694444
1936,Belém,0,1,1,10.43,0.000000,0.095877,0.095877
1937,São Domingos de Benfica,3,1,5,4.29,0.699301,0.233100,1.165501
1938,Campolide,1,1,1,2.77,0.361011,0.361011,0.361011
1939,Carnide,2,0,2,3.69,0.542005,0.000000,0.542005
1949,São Vicente,1,1,1,1.99,0.502513,0.502513,0.502513
1951,Estrela,0,3,7,4.60,0.000000,0.652174,1.521739

In [22]:
path_ensino = os.path.join(raw_path, 'ensino_superior', 'ensino_superior.csv')
ensino_superior = pd.read_csv(path_ensino)

ensino_superior_freg = (
    ensino_superior
    .groupby('Freguesia')
    .size()
    .reset_index(name='Num_Estabelecimentos_Ensino_Superior')
)
ensino_superior_freg

# merge com freguesias_lisboa sem adiconar coluna Freguesia duas vezes
freguesias_lisboa = freguesias_lisboa.merge(
    ensino_superior_freg,
    left_on='freguesia',
    right_on='Freguesia',
    how='left'
).drop(columns=['Freguesia'])

freguesias_lisboa['Num_Estabelecimentos_Ensino_Superior'] = freguesias_lisboa['Num_Estabelecimentos_Ensino_Superior'].fillna(0).astype(int)
freguesias_lisboa['Densidade_Estabelecimentos_Ensino_Superior_km2'] = freguesias_lisboa['Num_Estabelecimentos_Ensino_Superior'] / freguesias_lisboa['Area_km2']
freguesias_lisboa

,freguesia,Num_Estacoes_Metro,Num_Estacoes_Comboio,Num_Prestadores_Saude,Area_km2,Densidade_Estacoes_Metro_km2,Densidade_Estacoes_Comboio_km2,Densidade_Prestadores_Saude_km2,Num_Estabelecimentos_Ensino_Superior,Densidade_Estabelecimentos_Ensino_Superior_km2
0,Lumiar,4,0,5,6.57,0.608828,0.000000,0.761035,1,0.152207
1,Avenidas Novas,6,1,5,2.99,2.006689,0.334448,1.672241,2,0.668896
2,Areeiro,1,0,0,1.74,0.574713,0.000000,0.000000,1,0.574713
3,Beato,1,1,0,2.48,0.403226,0.403226,0.000000,0,0.000000
4,Benfica,1,1,3,8.02,0.124688,0.124688,0.374065,3,0.374065
5,Misericórdia,1,1,5,2.19,0.456621,0.456621,2.283105,1,0.456621
6,Parque das Nações,2,1,1,5.44,0.367647,0.183824,0.183824,1,0.183824
7,Olivais,4,0,3,8.09,0.494438,0.000000,0.370828,0,0.000000
8,Marvila,2,2,2,7.12,0.280899,0.280899,0.280899,3,0.421348
9,Santa Clara,1,0,0,3.36,0.297619,0.000000,0.000000,0,0.000000
10,Alvalade,3,1,4,5.34,0.561798,0.187266,0.749064,12,2.247191
11,Penha de França,0,0,2,2.71,0.000000,0.000000,0.738007,0,0.000000
12,Santo António,3,0,6,1.49,2.013423,0.000000,4.026846,2,1.342282
13,Arroios,4,0,6,2.13,1.877934,0.000000,2.816901,3,1.408451
14,Santa Maria Maior,5,1,2,3.01,1.661130,0.332226,0.664452,2,0.664452
15,Campo de Ourique,0,0,2,1.65,0.000000,0.000000,1.212121,1,0.606061
16,Alcântara,0,0,4,5.07,0.000000,0.000000,0.788955,4,0.788955
17,Ajuda,0,0,2,2.88,0.000000,0.000000,0.694444,3,1.041667
18,Belém,0,1,1,10.43,0.000000,0.095877,0.095877,1,0.095877
19,São Domingos de Benfica,3,1,5,4.29,0.699301,0.233100,1.165501,7,1.631702
20,Campolide,1,1,1,2.77,0.361011,0.361011,0.361011,1,0.361011
21,Carnide,2,0,2,3.69,0.542005,0.000000,0.542005,1,0.271003
22,São Vicente,1,1,1,1.99,0.502513,0.502513,0.502513,0,0.000000
23,Estrela,0,3,7,4.60,0.000000,0.652174,1.521739,1,0.217391

In [23]:
### Escolas Públicas
public_schools_dir = os.path.join(raw_path, 'escolas_publicas')

escolas_pre_escolar = pd.read_csv(os.path.join(public_schools_dir, 'escola_publica_pre_escolar.csv'))
escolas_1_ciclo = pd.read_csv(os.path.join(public_schools_dir, 'escola_publica_1ciclo.csv'))
escolas_2_3_ciclo = pd.read_csv(os.path.join(public_schools_dir, 'escola_publica_2_3ciclo.csv'))
escolas_3_ciclo_secundario = pd.read_csv(os.path.join(public_schools_dir, 'escola_publica_3ciclo_secundario.csv'))
escolas_secundario = pd.read_csv(os.path.join(public_schools_dir, 'escola_publica_secundario.csv'))
escolas_publicas = pd.concat([
    escolas_pre_escolar,
    escolas_1_ciclo,
    escolas_2_3_ciclo,
    escolas_3_ciclo_secundario,
    escolas_secundario
])
escolas_publicas.head()

,Object ID,Id Tipo,Código SIG,Nome,Morada,Código Postal,Freguesia,Tipologia,Agrupamento,Telefone,Email,Site,Blogue,GlobalID,x,y,Website
0,1,2,4201103017001,Escola Básica de São João de Brito,"Rua Lopes de Mendonça, 4",1700-271,Alvalade,EB01,Alvalade,218401178,ebsjb@aealvalade.edu.pt,http://aealvalade.edu.pt/,NaN,02731f2f-0fd4-478b-adce-ea0c2d202daf,-1.017185e+06,4.686787e+06,NaN
1,3,2,1102208003001,Escola Básica Professora Aida Vieira,"Rua Professor Sedas Nunes, Escola",1600-597,Carnide,EB01,Bairro Padre Cruz,217169300,eb23bpc@gmail.com,http://aebpc.com/,NaN,113e9738-460c-4e0c-916e-653a5f10d8cb,-1.023317e+06,4.688448e+06,NaN
2,5,2,1102301001001,Jardim de Infância do Bairro Padre Cruz,"Rua Prof. Francisco Pereira de Moura, Jardim d...",1600-746,Carnide,JI,Bairro Padre Cruz,217153601,eb23bpc@gmail.com,http://aebpc.com/,NaN,490ac21f-ffcc-4ee8-a524-455e826fb83a,-1.022993e+06,4.688610e+06,NaN
3,7,2,1501103001001,Escola Básica Gaivotas,"Rua das Chagas, 28-40",1200-107,Misericórdia,EB01,Passos Manuel,211368654,info.eb1.gvt@abc.edu.pt,aepassosmanuel.pt/escolas/eb1-ji-gaivotas/,http://escolajigaivotas.blogspot.com/,08fa6682-cac3-4758-938d-6da40471904e,-1.018037e+06,4.680295e+06,NaN
4,8,2,1500802013001,Escola Básica Padre Abel Varzim,"Rua da Rosa, 168",1200-390,Misericórdia,EB01,Passos Manuel,213460886,info.eb1.pav@abc.edu.pt,http://aepassosmanuel.pt/escolas/eb1-ji-padre-...,http://escolajipav.blogspot.com/,1b999a67-a4de-45b7-a3af-d6a1780a6193,-1.018071e+06,4.680763e+06,NaN

In [24]:
## verificar duplicados (nomes das escolas)
escolas_publicas.duplicated().sum()

np.int64(8)

In [25]:
## tratar dos duplicados (remover duplicados, só deixar uma ocorrência)
escolas_publicas = escolas_publicas.drop_duplicates()
escolas_publicas = escolas_publicas.reset_index(drop=True)
escolas_publicas.head()

,Object ID,Id Tipo,Código SIG,Nome,Morada,Código Postal,Freguesia,Tipologia,Agrupamento,Telefone,Email,Site,Blogue,GlobalID,x,y,Website
0,1,2,4201103017001,Escola Básica de São João de Brito,"Rua Lopes de Mendonça, 4",1700-271,Alvalade,EB01,Alvalade,218401178,ebsjb@aealvalade.edu.pt,http://aealvalade.edu.pt/,NaN,02731f2f-0fd4-478b-adce-ea0c2d202daf,-1.017185e+06,4.686787e+06,NaN
1,3,2,1102208003001,Escola Básica Professora Aida Vieira,"Rua Professor Sedas Nunes, Escola",1600-597,Carnide,EB01,Bairro Padre Cruz,217169300,eb23bpc@gmail.com,http://aebpc.com/,NaN,113e9738-460c-4e0c-916e-653a5f10d8cb,-1.023317e+06,4.688448e+06,NaN
2,5,2,1102301001001,Jardim de Infância do Bairro Padre Cruz,"Rua Prof. Francisco Pereira de Moura, Jardim d...",1600-746,Carnide,JI,Bairro Padre Cruz,217153601,eb23bpc@gmail.com,http://aebpc.com/,NaN,490ac21f-ffcc-4ee8-a524-455e826fb83a,-1.022993e+06,4.688610e+06,NaN
3,7,2,1501103001001,Escola Básica Gaivotas,"Rua das Chagas, 28-40",1200-107,Misericórdia,EB01,Passos Manuel,211368654,info.eb1.gvt@abc.edu.pt,aepassosmanuel.pt/escolas/eb1-ji-gaivotas/,http://escolajigaivotas.blogspot.com/,08fa6682-cac3-4758-938d-6da40471904e,-1.018037e+06,4.680295e+06,NaN
4,8,2,1500802013001,Escola Básica Padre Abel Varzim,"Rua da Rosa, 168",1200-390,Misericórdia,EB01,Passos Manuel,213460886,info.eb1.pav@abc.edu.pt,http://aepassosmanuel.pt/escolas/eb1-ji-padre-...,http://escolajipav.blogspot.com/,1b999a67-a4de-45b7-a3af-d6a1780a6193,-1.018071e+06,4.680763e+06,NaN

In [26]:
# Num_Escolas_Publicas em freguesias de lisboa
escolas_publicas_freg = (
    escolas_publicas
    .groupby('Freguesia')
    .size()
    .reset_index(name='Num_Escolas_Publicas')
)
escolas_publicas_freg

                  Freguesia  Num_Escolas_Publicas
0                     Ajuda                     6
1                 Alcântara                     7
2                  Alvalade                    15
3                   Areeiro                     4
4                   Arroios                     8
5            Avenidas Novas                     5
6                     Beato                     8
7                     Belém                    10
8                   Benfica                    14
9          Campo de Ourique                    13
10                Campolide                     4
11                  Carnide                    10
12                  Estrela                     3
13                   Lumiar                    17
14                  Marvila                    19
15             Misericórdia                     7
16                  Olivais                    19
17        Parque das Nações                     8
18          Penha de França                    10
19              Santa Clara                    11
20        Santa Maria Maior                     4
21            Santo António                     4
22  São Domingos de Benfica                     7
23              São Vicente                     6

In [27]:
## merge com freguesias_lisboa sem adiconar coluna Freguesia duas vezes
freguesias_lisboa = freguesias_lisboa.merge(
    escolas_publicas_freg,
    left_on='freguesia',
    right_on='Freguesia',
    how='left'
).drop(columns=['Freguesia'])
freguesias_lisboa['Num_Escolas_Publicas'] = freguesias_lisboa['Num_Escolas_Publicas'].fillna(0).astype(int)

# fazer densidade de escolas públicas por km2
freguesias_lisboa['Densidade_Escolas_Publicas_km2'] = freguesias_lisboa['Num_Escolas_Publicas'] / freguesias_lisboa['Area_km2']
freguesias_lisboa

,freguesia,Num_Estacoes_Metro,Num_Estacoes_Comboio,Num_Prestadores_Saude,Area_km2,Densidade_Estacoes_Metro_km2,Densidade_Estacoes_Comboio_km2,Densidade_Prestadores_Saude_km2,Num_Estabelecimentos_Ensino_Superior,Densidade_Estabelecimentos_Ensino_Superior_km2,Num_Escolas_Publicas,Densidade_Escolas_Publicas_km2
0,Lumiar,4,0,5,6.57,0.608828,0.000000,0.761035,1,0.152207,17,2.587519
1,Avenidas Novas,6,1,5,2.99,2.006689,0.334448,1.672241,2,0.668896,5,1.672241
2,Areeiro,1,0,0,1.74,0.574713,0.000000,0.000000,1,0.574713,4,2.298851
3,Beato,1,1,0,2.48,0.403226,0.403226,0.000000,0,0.000000,8,3.225806
4,Benfica,1,1,3,8.02,0.124688,0.124688,0.374065,3,0.374065,14,1.745636
5,Misericórdia,1,1,5,2.19,0.456621,0.456621,2.283105,1,0.456621,7,3.196347
6,Parque das Nações,2,1,1,5.44,0.367647,0.183824,0.183824,1,0.183824,8,1.470588
7,Olivais,4,0,3,8.09,0.494438,0.000000,0.370828,0,0.000000,19,2.348578
8,Marvila,2,2,2,7.12,0.280899,0.280899,0.280899,3,0.421348,19,2.668539
9,Santa Clara,1,0,0,3.36,0.297619,0.000000,0.000000,0,0.000000,11,3.273810
10,Alvalade,3,1,4,5.34,0.561798,0.187266,0.749064,12,2.247191,15,2.808989
11,Penha de França,0,0,2,2.71,0.000000,0.000000,0.738007,0,0.000000,10,3.690037
12,Santo António,3,0,6,1.49,2.013423,0.000000,4.026846,2,1.342282,4,2.684564
13,Arroios,4,0,6,2.13,1.877934,0.000000,2.816901,3,1.408451,8,3.755869
14,Santa Maria Maior,5,1,2,3.01,1.661130,0.332226,0.664452,2,0.664452,4,1.328904
15,Campo de Ourique,0,0,2,1.65,0.000000,0.000000,1.212121,1,0.606061,13,7.878788
16,Alcântara,0,0,4,5.07,0.000000,0.000000,0.788955,4,0.788955,7,1.380671
17,Ajuda,0,0,2,2.88,0.000000,0.000000,0.694444,3,1.041667,6,2.083333
18,Belém,0,1,1,10.43,0.000000,0.095877,0.095877,1,0.095877,10,0.958773
19,São Domingos de Benfica,3,1,5,4.29,0.699301,0.233100,1.165501,7,1.631702,7,1.631702
20,Campolide,1,1,1,2.77,0.361011,0.361011,0.361011,1,0.361011,4,1.444043
21,Carnide,2,0,2,3.69,0.542005,0.000000,0.542005,1,0.271003,10,2.710027
22,São Vicente,1,1,1,1.99,0.502513,0.502513,0.502513,0,0.000000,6,3.015075
23,Estrela,0,3,7,4.60,0.000000,0.652174,1.521739,1,0.217391,3,0.652174

In [28]:
### Escolas Privadas
private_schools_dir = os.path.join(raw_path, 'escolas_privadas')
escolas_pre_escolar = pd.read_csv(os.path.join(private_schools_dir, 'escola_privada_pre_escolar.csv'))
escolas_1_ciclo = pd.read_csv(os.path.join(private_schools_dir, 'escola_privada_1ciclo.csv'))
escolas_2_3_ciclo = pd.read_csv(os.path.join(private_schools_dir, 'escola_privada_2_3ciclo.csv'))
escolas_secundario = pd.read_csv(os.path.join(private_schools_dir, 'escola_privada_secundario.csv'))
escolas_privadas = pd.concat([
    escolas_pre_escolar,
    escolas_1_ciclo,
    escolas_2_3_ciclo,
    escolas_secundario
])
escolas_privadas.head()

,OBJECTID,Id Tipo,Código SIG,Nome,Morada,Freguesia,Telefone,Email,Site,Ativo,GlobalID,x,y,Website
0,2,14000,1554,Colégio do Bom Sucesso,"Rua Bartolomeu Dias, 53\n",Belém,213010442,cl.bomsucesso@escolas.min-edu.pt;,https://www.colegiobomsucesso.pt/,1,5a37b6df-a24a-4d75-a71d-eddc6686936e,-1.025370e+06,4.678159e+06,NaN
1,3,14000,1555,"Cooperativa """"A Torre""""",Praça Malaca n.º 2,Belém,+351 213 011 407,ext.atorre@escolas.min-edu.pt; geral@atorre.pt,https://atorre.pt/,1,8e20c9e7-5dac-447f-afe7-8c330fd13faa,-1.026119e+06,4.678256e+06,NaN
2,4,14000,1556,"Externato """"A Escolinha""""","Rua Fernão Mendes Pinto, 41",Belém,+351 213 014 452,ext.aescolinha@escolas.min-edu.pt,https://www.externatoescolinha.pt/,1,2f49fb56-1ae4-4f3a-a571-8633e02c9278,-1.026911e+06,4.678407e+06,NaN
3,7,14000,1559,Abrigo Infantil de Stª Mª de Belém - Centro Pa...,"Largo dos Jerónimos, 3 - 2º",Belém,+351 21 363 4242,abrigo.stmariabelem@gmail.com,NaN,1,e20f7c49-f3b7-42d3-8001-b0e4bf607fed,-1.024646e+06,4.678531e+06,NaN
4,8,14000,1560,Escola Raiz,"Avenida Torre de Belém, 30",Belém,+351 213 042 080,esc.raiz@escolas.min-edu.pt,https://escolaraiz.pt/,1,df6907ce-b395-46fb-8a46-fb39181fd481,-1.025684e+06,4.678664e+06,NaN

In [29]:
## verificar duplicados (nomes das escolas)
escolas_privadas.duplicated().sum()

np.int64(0)

In [30]:
# Num_Escolas_Privadas em freguesias de lisboa
escolas_privadas_freg = (
    escolas_privadas
    .groupby('Freguesia')
    .size()
    .reset_index(name='Num_Escolas_Privadas')
)
escolas_privadas_freg

                  Freguesia  Num_Escolas_Privadas
0                     Ajuda                     8
1                 Alcântara                     7
2                  Alvalade                    39
3                   Areeiro                    10
4                   Arroios                    27
5            Avenidas Novas                    17
6                     Belém                    41
7                   Benfica                    17
8          Campo de Ourique                    21
9                 Campolide                     9
10                  Carnide                     8
11                  Estrela                    16
12                   Lumiar                    37
13                  Marvila                    18
14             Misericórdia                     6
15                  Olivais                    18
16        Parque das Nações                    16
17          Penha de França                     9
18              Santa Clara                    11
19        Santa Maria Maior                     3
20  São Domingos de Benfica                    24
21              São Vicente                     7

In [31]:
## merge com freguesias_lisboa sem adiconar coluna Freguesia duas vezes
freguesias_lisboa = freguesias_lisboa.merge(
    escolas_privadas_freg,
    left_on='freguesia',
    right_on='Freguesia',
    how='left'
).drop(columns=['Freguesia'])
freguesias_lisboa['Num_Escolas_Privadas'] = freguesias_lisboa['Num_Escolas_Privadas'].fillna(0).astype(int)

# fazer densidade de escolas privadas por km2
freguesias_lisboa['Densidade_Escolas_Privadas_km2'] = freguesias_lisboa['Num_Escolas_Privadas'] / freguesias_lisboa['Area_km2']
freguesias_lisboa

,freguesia,Num_Estacoes_Metro,Num_Estacoes_Comboio,Num_Prestadores_Saude,Area_km2,Densidade_Estacoes_Metro_km2,Densidade_Estacoes_Comboio_km2,Densidade_Prestadores_Saude_km2,Num_Estabelecimentos_Ensino_Superior,Densidade_Estabelecimentos_Ensino_Superior_km2,Num_Escolas_Publicas,Densidade_Escolas_Publicas_km2,Num_Escolas_Privadas,Densidade_Escolas_Privadas_km2
0,Lumiar,4,0,5,6.57,0.608828,0.000000,0.761035,1,0.152207,17,2.587519,37,5.631659
1,Avenidas Novas,6,1,5,2.99,2.006689,0.334448,1.672241,2,0.668896,5,1.672241,17,5.685619
2,Areeiro,1,0,0,1.74,0.574713,0.000000,0.000000,1,0.574713,4,2.298851,10,5.747126
3,Beato,1,1,0,2.48,0.403226,0.403226,0.000000,0,0.000000,8,3.225806,0,0.000000
4,Benfica,1,1,3,8.02,0.124688,0.124688,0.374065,3,0.374065,14,1.745636,17,2.119701
5,Misericórdia,1,1,5,2.19,0.456621,0.456621,2.283105,1,0.456621,7,3.196347,6,2.739726
6,Parque das Nações,2,1,1,5.44,0.367647,0.183824,0.183824,1,0.183824,8,1.470588,16,2.941176
7,Olivais,4,0,3,8.09,0.494438,0.000000,0.370828,0,0.000000,19,2.348578,18,2.224969
8,Marvila,2,2,2,7.12,0.280899,0.280899,0.280899,3,0.421348,19,2.668539,18,2.528090
9,Santa Clara,1,0,0,3.36,0.297619,0.000000,0.000000,0,0.000000,11,3.273810,11,3.273810
10,Alvalade,3,1,4,5.34,0.561798,0.187266,0.749064,12,2.247191,15,2.808989,39,7.303371
11,Penha de França,0,0,2,2.71,0.000000,0.000000,0.738007,0,0.000000,10,3.690037,9,3.321033
12,Santo António,3,0,6,1.49,2.013423,0.000000,4.026846,2,1.342282,4,2.684564,0,0.000000
13,Arroios,4,0,6,2.13,1.877934,0.000000,2.816901,3,1.408451,8,3.755869,27,12.676056
14,Santa Maria Maior,5,1,2,3.01,1.661130,0.332226,0.664452,2,0.664452,4,1.328904,3,0.996678
15,Campo de Ourique,0,0,2,1.65,0.000000,0.000000,1.212121,1,0.606061,13,7.878788,21,12.727273
16,Alcântara,0,0,4,5.07,0.000000,0.000000,0.788955,4,0.788955,7,1.380671,7,1.380671
17,Ajuda,0,0,2,2.88,0.000000,0.000000,0.694444,3,1.041667,6,2.083333,8,2.777778
18,Belém,0,1,1,10.43,0.000000,0.095877,0.095877,1,0.095877,10,0.958773,41,3.930968
19,São Domingos de Benfica,3,1,5,4.29,0.699301,0.233100,1.165501,7,1.631702,7,1.631702,24,5.594406
20,Campolide,1,1,1,2.77,0.361011,0.361011,0.361011,1,0.361011,4,1.444043,9,3.249097
21,Carnide,2,0,2,3.69,0.542005,0.000000,0.542005,1,0.271003,10,2.710027,8,2.168022
22,São Vicente,1,1,1,1.99,0.502513,0.502513,0.502513,0,0.000000,6,3.015075,7,3.517588
23,Estrela,0,3,7,4.60,0.000000,0.652174,1.521739,1,0.217391,3,0.652174,16,3.478261

In [32]:
## jardins parques urbanos
path_jardins = os.path.join(raw_path, 'jardins_parques_urbanos', 'Jardins_-_Parques_Urbanos.csv')
jardins_parques = pd.read_csv(path_jardins)

In [33]:
jardins_freg = (
    jardins_parques
    .groupby('FREGUESIA')
    .size()
    .reset_index(name='Num_Jardins_Parques_Urbanos')
)

## merge com freguesias_lisboa sem adiconar coluna Freguesia duas vezes
freguesias_lisboa = freguesias_lisboa.merge(
    jardins_freg,
    left_on='freguesia',
    right_on='FREGUESIA',
    how='left'
).drop(columns=['FREGUESIA'])

freguesias_lisboa['Num_Jardins_Parques_Urbanos'] = freguesias_lisboa['Num_Jardins_Parques_Urbanos'].fillna(0).astype(int)
freguesias_lisboa['Densidade_Jardins_Parques_Urbanos_km2'] = freguesias_lisboa['Num_Jardins_Parques_Urbanos'] / freguesias_lisboa['Area_km2']
freguesias_lisboa

,freguesia,Num_Estacoes_Metro,Num_Estacoes_Comboio,Num_Prestadores_Saude,Area_km2,Densidade_Estacoes_Metro_km2,Densidade_Estacoes_Comboio_km2,Densidade_Prestadores_Saude_km2,Num_Estabelecimentos_Ensino_Superior,Densidade_Estabelecimentos_Ensino_Superior_km2,Num_Escolas_Publicas,Densidade_Escolas_Publicas_km2,Num_Escolas_Privadas,Densidade_Escolas_Privadas_km2,Num_Jardins_Parques_Urbanos,Densidade_Jardins_Parques_Urbanos_km2
0,Lumiar,4,0,5,6.57,0.608828,0.000000,0.761035,1,0.152207,17,2.587519,37,5.631659,7,1.065449
1,Avenidas Novas,6,1,5,2.99,2.006689,0.334448,1.672241,2,0.668896,5,1.672241,17,5.685619,9,3.010033
2,Areeiro,1,0,0,1.74,0.574713,0.000000,0.000000,1,0.574713,4,2.298851,10,5.747126,8,4.597701
3,Beato,1,1,0,2.48,0.403226,0.403226,0.000000,0,0.000000,8,3.225806,0,0.000000,1,0.403226
4,Benfica,1,1,3,8.02,0.124688,0.124688,0.374065,3,0.374065,14,1.745636,17,2.119701,7,0.872818
5,Misericórdia,1,1,5,2.19,0.456621,0.456621,2.283105,1,0.456621,7,3.196347,6,2.739726,6,2.739726
6,Parque das Nações,2,1,1,5.44,0.367647,0.183824,0.183824,1,0.183824,8,1.470588,16,2.941176,7,1.286765
7,Olivais,4,0,3,8.09,0.494438,0.000000,0.370828,0,0.000000,19,2.348578,18,2.224969,7,0.865266
8,Marvila,2,2,2,7.12,0.280899,0.280899,0.280899,3,0.421348,19,2.668539,18,2.528090,8,1.123596
9,Santa Clara,1,0,0,3.36,0.297619,0.000000,0.000000,0,0.000000,11,3.273810,11,3.273810,5,1.488095
10,Alvalade,3,1,4,5.34,0.561798,0.187266,0.749064,12,2.247191,15,2.808989,39,7.303371,8,1.498127
11,Penha de França,0,0,2,2.71,0.000000,0.000000,0.738007,0,0.000000,10,3.690037,9,3.321033,0,0.000000
12,Santo António,3,0,6,1.49,2.013423,0.000000,4.026846,2,1.342282,4,2.684564,0,0.000000,5,3.355705
13,Arroios,4,0,6,2.13,1.877934,0.000000,2.816901,3,1.408451,8,3.755869,27,12.676056,6,2.816901
14,Santa Maria Maior,5,1,2,3.01,1.661130,0.332226,0.664452,2,0.664452,4,1.328904,3,0.996678,2,0.664452
15,Campo de Ourique,0,0,2,1.65,0.000000,0.000000,1.212121,1,0.606061,13,7.878788,21,12.727273,2,1.212121
16,Alcântara,0,0,4,5.07,0.000000,0.000000,0.788955,4,0.788955,7,1.380671,7,1.380671,7,1.380671
17,Ajuda,0,0,2,2.88,0.000000,0.000000,0.694444,3,1.041667,6,2.083333,8,2.777778,6,2.083333
18,Belém,0,1,1,10.43,0.000000,0.095877,0.095877,1,0.095877,10,0.958773,41,3.930968,12,1.150527
19,São Domingos de Benfica,3,1,5,4.29,0.699301,0.233100,1.165501,7,1.631702,7,1.631702,24,5.594406,8,1.864802
20,Campolide,1,1,1,2.77,0.361011,0.361011,0.361011,1,0.361011,4,1.444043,9,3.249097,5,1.805054
21,Carnide,2,0,2,3.69,0.542005,0.000000,0.542005,1,0.271003,10,2.710027,8,2.168022,5,1.355014
22,São Vicente,1,1,1,1.99,0.502513,0.502513,0.502513,0,0.000000,6,3.015075,7,3.517588,5,2.512563
23,Estrela,0,3,7,4.60,0.000000,0.652174,1.521739,1,0.217391,3,0.652174,16,3.478261,10,2.173913

In [34]:
## museus
path_museus = os.path.join(raw_path, 'museus', 'museus.csv')
museus = pd.read_csv(path_museus)
museus_freg = (
    museus
    .groupby('Freguesia')
    .size()
    .reset_index(name='Num_Museus')
)

## merge com freguesias_lisboa sem adiconar coluna Freguesia duas vezes
freguesias_lisboa = freguesias_lisboa.merge(
    museus_freg,
    left_on='freguesia',
    right_on='Freguesia',
    how='left'
).drop(columns=['Freguesia'])

freguesias_lisboa['Num_Museus'] = freguesias_lisboa['Num_Museus'].fillna(0).astype(int)
freguesias_lisboa['Densidade_Museus_km2'] = freguesias_lisboa['Num_Museus'] / freguesias_lisboa['Area_km2']
freguesias_lisboa

,freguesia,Num_Estacoes_Metro,Num_Estacoes_Comboio,Num_Prestadores_Saude,Area_km2,Densidade_Estacoes_Metro_km2,Densidade_Estacoes_Comboio_km2,Densidade_Prestadores_Saude_km2,Num_Estabelecimentos_Ensino_Superior,Densidade_Estabelecimentos_Ensino_Superior_km2,Num_Escolas_Publicas,Densidade_Escolas_Publicas_km2,Num_Escolas_Privadas,Densidade_Escolas_Privadas_km2,Num_Jardins_Parques_Urbanos,Densidade_Jardins_Parques_Urbanos_km2,Num_Museus,Densidade_Museus_km2
0,Lumiar,4,0,5,6.57,0.608828,0.000000,0.761035,1,0.152207,17,2.587519,37,5.631659,7,1.065449,2,0.304414
1,Avenidas Novas,6,1,5,2.99,2.006689,0.334448,1.672241,2,0.668896,5,1.672241,17,5.685619,9,3.010033,3,1.003344
2,Areeiro,1,0,0,1.74,0.574713,0.000000,0.000000,1,0.574713,4,2.298851,10,5.747126,8,4.597701,0,0.000000
3,Beato,1,1,0,2.48,0.403226,0.403226,0.000000,0,0.000000,8,3.225806,0,0.000000,1,0.403226,0,0.000000
4,Benfica,1,1,3,8.02,0.124688,0.124688,0.374065,3,0.374065,14,1.745636,17,2.119701,7,0.872818,0,0.000000
5,Misericórdia,1,1,5,2.19,0.456621,0.456621,2.283105,1,0.456621,7,3.196347,6,2.739726,6,2.739726,7,3.196347
6,Parque das Nações,2,1,1,5.44,0.367647,0.183824,0.183824,1,0.183824,8,1.470588,16,2.941176,7,1.286765,1,0.183824
7,Olivais,4,0,3,8.09,0.494438,0.000000,0.370828,0,0.000000,19,2.348578,18,2.224969,7,0.865266,0,0.000000
8,Marvila,2,2,2,7.12,0.280899,0.280899,0.280899,3,0.421348,19,2.668539,18,2.528090,8,1.123596,1,0.140449
9,Santa Clara,1,0,0,3.36,0.297619,0.000000,0.000000,0,0.000000,11,3.273810,11,3.273810,5,1.488095,0,0.000000
10,Alvalade,3,1,4,5.34,0.561798,0.187266,0.749064,12,2.247191,15,2.808989,39,7.303371,8,1.498127,3,0.561798
11,Penha de França,0,0,2,2.71,0.000000,0.000000,0.738007,0,0.000000,10,3.690037,9,3.321033,0,0.000000,1,0.369004
12,Santo António,3,0,6,1.49,2.013423,0.000000,4.026846,2,1.342282,4,2.684564,0,0.000000,5,3.355705,4,2.684564
13,Arroios,4,0,6,2.13,1.877934,0.000000,2.816901,3,1.408451,8,3.755869,27,12.676056,6,2.816901,1,0.469484
14,Santa Maria Maior,5,1,2,3.01,1.661130,0.332226,0.664452,2,0.664452,4,1.328904,3,0.996678,2,0.664452,18,5.980066
15,Campo de Ourique,0,0,2,1.65,0.000000,0.000000,1.212121,1,0.606061,13,7.878788,21,12.727273,2,1.212121,3,1.818182
16,Alcântara,0,0,4,5.07,0.000000,0.000000,0.788955,4,0.788955,7,1.380671,7,1.380671,7,1.380671,2,0.394477
17,Ajuda,0,0,2,2.88,0.000000,0.000000,0.694444,3,1.041667,6,2.083333,8,2.777778,6,2.083333,0,0.000000
18,Belém,0,1,1,10.43,0.000000,0.095877,0.095877,1,0.095877,10,0.958773,41,3.930968,12,1.150527,9,0.862895
19,São Domingos de Benfica,3,1,5,4.29,0.699301,0.233100,1.165501,7,1.631702,7,1.631702,24,5.594406,8,1.864802,3,0.699301
20,Campolide,1,1,1,2.77,0.361011,0.361011,0.361011,1,0.361011,4,1.444043,9,3.249097,5,1.805054,0,0.000000
21,Carnide,2,0,2,3.69,0.542005,0.000000,0.542005,1,0.271003,10,2.710027,8,2.168022,5,1.355014,0,0.000000
22,São Vicente,1,1,1,1.99,0.502513,0.502513,0.502513,0,0.000000,6,3.015075,7,3.517588,5,2.512563,2,1.005025
23,Estrela,0,3,7,4.60,0.000000,0.652174,1.521739,1,0.217391,3,0.652174,16,3.478261,10,2.173913,3,0.652174

In [35]:
## mercados
path_mercados= os.path.join(raw_path, 'mercados', 'mercados.csv')
mercados = pd.read_csv(path_mercados)
mercados_freg = (
    mercados
    .groupby('Freguesia')
    .size()
    .reset_index(name='Num_Mercados')
)

## merge com freguesias_lisboa sem adiconar coluna Freguesia duas vezes
freguesias_lisboa = freguesias_lisboa.merge(
    mercados_freg,
    left_on='freguesia',
    right_on='Freguesia',
    how='left'
).drop(columns=['Freguesia'])

freguesias_lisboa['Num_Mercados'] = freguesias_lisboa['Num_Mercados'].fillna(0).astype(int)
freguesias_lisboa['Densidade_Mercados_km2'] = freguesias_lisboa['Num_Mercados'] / freguesias_lisboa['Area_km2']
freguesias_lisboa

,freguesia,Num_Estacoes_Metro,Num_Estacoes_Comboio,Num_Prestadores_Saude,Area_km2,Densidade_Estacoes_Metro_km2,Densidade_Estacoes_Comboio_km2,Densidade_Prestadores_Saude_km2,Num_Estabelecimentos_Ensino_Superior,Densidade_Estabelecimentos_Ensino_Superior_km2,Num_Escolas_Publicas,Densidade_Escolas_Publicas_km2,Num_Escolas_Privadas,Densidade_Escolas_Privadas_km2,Num_Jardins_Parques_Urbanos,Densidade_Jardins_Parques_Urbanos_km2,Num_Museus,Densidade_Museus_km2,Num_Mercados,Densidade_Mercados_km2
0,Lumiar,4,0,5,6.57,0.608828,0.000000,0.761035,1,0.152207,17,2.587519,37,5.631659,7,1.065449,2,0.304414,0,0.000000
1,Avenidas Novas,6,1,5,2.99,2.006689,0.334448,1.672241,2,0.668896,5,1.672241,17,5.685619,9,3.010033,3,1.003344,1,0.334448
2,Areeiro,1,0,0,1.74,0.574713,0.000000,0.000000,1,0.574713,4,2.298851,10,5.747126,8,4.597701,0,0.000000,1,0.574713
3,Beato,1,1,0,2.48,0.403226,0.403226,0.000000,0,0.000000,8,3.225806,0,0.000000,1,0.403226,0,0.000000,1,0.403226
4,Benfica,1,1,3,8.02,0.124688,0.124688,0.374065,3,0.374065,14,1.745636,17,2.119701,7,0.872818,0,0.000000,2,0.249377
5,Misericórdia,1,1,5,2.19,0.456621,0.456621,2.283105,1,0.456621,7,3.196347,6,2.739726,6,2.739726,7,3.196347,1,0.456621
6,Parque das Nações,2,1,1,5.44,0.367647,0.183824,0.183824,1,0.183824,8,1.470588,16,2.941176,7,1.286765,1,0.183824,0,0.000000
7,Olivais,4,0,3,8.09,0.494438,0.000000,0.370828,0,0.000000,19,2.348578,18,2.224969,7,0.865266,0,0.000000,0,0.000000
8,Marvila,2,2,2,7.12,0.280899,0.280899,0.280899,3,0.421348,19,2.668539,18,2.528090,8,1.123596,1,0.140449,1,0.140449
9,Santa Clara,1,0,0,3.36,0.297619,0.000000,0.000000,0,0.000000,11,3.273810,11,3.273810,5,1.488095,0,0.000000,0,0.000000
10,Alvalade,3,1,4,5.34,0.561798,0.187266,0.749064,12,2.247191,15,2.808989,39,7.303371,8,1.498127,3,0.561798,2,0.374532
11,Penha de França,0,0,2,2.71,0.000000,0.000000,0.738007,0,0.000000,10,3.690037,9,3.321033,0,0.000000,1,0.369004,0,0.000000
12,Santo António,3,0,6,1.49,2.013423,0.000000,4.026846,2,1.342282,4,2.684564,0,0.000000,5,3.355705,4,2.684564,0,0.000000
13,Arroios,4,0,6,2.13,1.877934,0.000000,2.816901,3,1.408451,8,3.755869,27,12.676056,6,2.816901,1,0.469484,1,0.469484
14,Santa Maria Maior,5,1,2,3.01,1.661130,0.332226,0.664452,2,0.664452,4,1.328904,3,0.996678,2,0.664452,18,5.980066,0,0.000000
15,Campo de Ourique,0,0,2,1.65,0.000000,0.000000,1.212121,1,0.606061,13,7.878788,21,12.727273,2,1.212121,3,1.818182,1,0.606061
16,Alcântara,0,0,4,5.07,0.000000,0.000000,0.788955,4,0.788955,7,1.380671,7,1.380671,7,1.380671,2,0.394477,1,0.197239
17,Ajuda,0,0,2,2.88,0.000000,0.000000,0.694444,3,1.041667,6,2.083333,8,2.777778,6,2.083333,0,0.000000,0,0.000000
18,Belém,0,1,1,10.43,0.000000,0.095877,0.095877,1,0.095877,10,0.958773,41,3.930968,12,1.150527,9,0.862895,0,0.000000
19,São Domingos de Benfica,3,1,5,4.29,0.699301,0.233100,1.165501,7,1.631702,7,1.631702,24,5.594406,8,1.864802,3,0.699301,1,0.233100
20,Campolide,1,1,1,2.77,0.361011,0.361011,0.361011,1,0.361011,4,1.444043,9,3.249097,5,1.805054,0,0.000000,0,0.000000
21,Carnide,2,0,2,3.69,0.542005,0.000000,0.542005,1,0.271003,10,2.710027,8,2.168022,5,1.355014,0,0.000000,1,0.271003
22,São Vicente,1,1,1,1.99,0.502513,0.502513,0.502513,0,0.000000,6,3.015075,7,3.517588,5,2.512563,2,1.005025,0,0.000000
23,Estrela,0,3,7,4.60,0.000000,0.652174,1.521739,1,0.217391,3,0.652174,16,3.478261,10,2.173913,3,0.652174,0,0.000000

In [36]:
## supermercados
path_supermercados = os.path.join(raw_path, 'supermercados', 'supermercados.csv')
supermercados = pd.read_csv(path_supermercados)
supermercados_freg = (
    supermercados
    .groupby('FREGUESIA')
    .size()
    .reset_index(name='Num_Supermercados')
)

## merge com freguesias_lisboa sem adiconar coluna Freguesia duas vezes
freguesias_lisboa = freguesias_lisboa.merge(
    supermercados_freg,
    left_on='freguesia',
    right_on='FREGUESIA',
    how='left'
).drop(columns=['FREGUESIA'])

freguesias_lisboa['Num_Supermercados'] = freguesias_lisboa['Num_Supermercados'].fillna(0).astype(int)
freguesias_lisboa['Densidade_Supermercados_km2'] = freguesias_lisboa['Num_Supermercados'] / freguesias_lisboa['Area_km2']
freguesias_lisboa

,freguesia,Num_Estacoes_Metro,Num_Estacoes_Comboio,Num_Prestadores_Saude,Area_km2,Densidade_Estacoes_Metro_km2,Densidade_Estacoes_Comboio_km2,Densidade_Prestadores_Saude_km2,Num_Estabelecimentos_Ensino_Superior,Densidade_Estabelecimentos_Ensino_Superior_km2,...,Num_Escolas_Privadas,Densidade_Escolas_Privadas_km2,Num_Jardins_Parques_Urbanos,Densidade_Jardins_Parques_Urbanos_km2,Num_Museus,Densidade_Museus_km2,Num_Mercados,Densidade_Mercados_km2,Num_Supermercados,Densidade_Supermercados_km2
0,Lumiar,4,0,5,6.57,0.608828,0.000000,0.761035,1,0.152207,...,37,5.631659,7,1.065449,2,0.304414,0,0.000000,7,1.065449
1,Avenidas Novas,6,1,5,2.99,2.006689,0.334448,1.672241,2,0.668896,...,17,5.685619,9,3.010033,3,1.003344,1,0.334448,10,3.344482
2,Areeiro,1,0,0,1.74,0.574713,0.000000,0.000000,1,0.574713,...,10,5.747126,8,4.597701,0,0.000000,1,0.574713,7,4.022989
3,Beato,1,1,0,2.48,0.403226,0.403226,0.000000,0,0.000000,...,0,0.000000,1,0.403226,0,0.000000,1,0.403226,1,0.403226
4,Benfica,1,1,3,8.02,0.124688,0.124688,0.374065,3,0.374065,...,17,2.119701,7,0.872818,0,0.000000,2,0.249377,4,0.498753
5,Misericórdia,1,1,5,2.19,0.456621,0.456621,2.283105,1,0.456621,...,6,2.739726,6,2.739726,7,3.196347,1,0.456621,1,0.456621
6,Parque das Nações,2,1,1,5.44,0.367647,0.183824,0.183824,1,0.183824,...,16,2.941176,7,1.286765,1,0.183824,0,0.000000,2,0.367647
7,Olivais,4,0,3,8.09,0.494438,0.000000,0.370828,0,0.000000,...,18,2.224969,7,0.865266,0,0.000000,0,0.000000,2,0.247219
8,Marvila,2,2,2,7.12,0.280899,0.280899,0.280899,3,0.421348,...,18,2.528090,8,1.123596,1,0.140449,1,0.140449,2,0.280899
9,Santa Clara,1,0,0,3.36,0.297619,0.000000,0.000000,0,0.000000,...,11,3.273810,5,1.488095,0,0.000000,0,0.000000,0,0.000000
10,Alvalade,3,1,4,5.34,0.561798,0.187266,0.749064,12,2.247191,...,39,7.303371,8,1.498127,3,0.561798,2,0.374532,3,0.561798
11,Penha de França,0,0,2,2.71,0.000000,0.000000,0.738007,0,0.000000,...,9,3.321033,0,0.000000,1,0.369004,0,0.000000,0,0.000000
12,Santo António,3,0,6,1.49,2.013423,0.000000,4.026846,2,1.342282,...,0,0.000000,5,3.355705,4,2.684564,0,0.000000,7,4.697987
13,Arroios,4,0,6,2.13,1.877934,0.000000,2.816901,3,1.408451,...,27,12.676056,6,2.816901,1,0.469484,1,0.469484,3,1.408451
14,Santa Maria Maior,5,1,2,3.01,1.661130,0.332226,0.664452,2,0.664452,...,3,0.996678,2,0.664452,18,5.980066,0,0.000000,4,1.328904
15,Campo de Ourique,0,0,2,1.65,0.000000,0.000000,1.212121,1,0.606061,...,21,12.727273,2,1.212121,3,1.818182,1,0.606061,2,1.212121
16,Alcântara,0,0,4,5.07,0.000000,0.000000,0.788955,4,0.788955,...,7,1.380671,7,1.380671,2,0.394477,1,0.197239,0,0.000000
17,Ajuda,0,0,2,2.88,0.000000,0.000000,0.694444,3,1.041667,...,8,2.777778,6,2.083333,0,0.000000,0,0.000000,1,0.347222
18,Belém,0,1,1,10.43,0.000000,0.095877,0.095877,1,0.095877,...,41,3.930968,12,1.150527,9,0.862895,0,0.000000,0,0.000000
19,São Domingos de Benfica,3,1,5,4.29,0.699301,0.233100,1.165501,7,1.631702,...,24,5.594406,8,1.864802,3,0.699301,1,0.233100,4,0.932401
20,Campolide,1,1,1,2.77,0.361011,0.361011,0.361011,1,0.361011,...,9,3.249097,5,1.805054,0,0.000000,0,0.000000,0,0.000000
21,Carnide,2,0,2,3.69,0.542005,0.000000,0.542005,1,0.271003,...,8,2.168022,5,1.355014,0,0.000000,1,0.271003,1,0.271003
22,São Vicente,1,1,1,1.99,0.502513,0.502513,0.502513,0,0.000000,...,7,3.517588,5,2.512563,2,1.005025,0,0.000000,0,0.000000
23,Estrela,0,3,7,4.60,0.000000,0.652174,1.521739,1,0.217391,...,16,3.478261,10,2.173913,3,0.652174,0,0.000000,0,0.000000

In [37]:
freguesias_lisboa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 22 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   freguesia                                       24 non-null     object
 1   Num_Estacoes_Metro                              24 non-null     int64
 2   Num_Estacoes_Comboio                            24 non-null     int64
 3   Num_Prestadores_Saude                           24 non-null     int64
 4   Area_km2                                        24 non-null     float64
 5   Densidade_Estacoes_Metro_km2                    24 non-null     float64
 6   Densidade_Estacoes_Comboio_km2                  24 non-null     float64
 7   Densidade_Prestadores_Saude_km2                 24 non-null     float64
 8   Num_Estabelecimentos_Ensino_Superior            24 non-null     int64
 9   Densidade_Estabelecimentos_Ensino_Superior_km2  24 non-null     float64
 10  Num_Escolas_Publicas                            24 non-null     int64
 11  Densidade_Escolas_Publicas_km2                  24 non-null     float64
 12  Num_Escolas_Privadas                            24 non-null     int64
 13  Densidade_Escolas_Privadas_km2                  24 non-null     float64
 14  Num_Jardins_Parques_Urbanos                     24 non-null     int64
 15  Densidade_Jardins_Parques_Urbanos_km2           24 non-null     float64
 16  Num_Museus                                      24 non-null     int64
 17  Densidade_Museus_km2                            24 non-null     float64
 18  Num_Mercados                                    24 non-null     int64
 19  Densidade_Mercados_km2                          24 non-null     float64
 20  Num_Supermercados                               24 non-null     int64
 21  Densidade_Supermercados_km2                     24 non-null     float64
dtypes: float64(11), int64(10), object(1)
memory usage: 4.3+ KB

In [38]:
output_path = os.path.join('..', 'data', 'processed', 'POIs_freguesias_lisboa.csv')
freguesias_lisboa.to_csv(output_path, index=False)